name: Build Alpine RootFS Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget e2fsprogs

      - name: Download Alpine rootfs
        run: |
          wget https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/armv7/alpine-minirootfs-3.23.3-armv7.tar.gz

      - name: Create image
        run: |
          dd if=/dev/zero of=alpine-root.img bs=1M count=1024
          mkfs.ext4 -F alpine-root.img

      - name: Mount image
        run: |
          mkdir mnt
          sudo mount -o loop alpine-root.img mnt

      - name: Extract rootfs
        run: |
          sudo tar -xpf alpine-minirootfs-3.23.3-armv7.tar.gz -C mnt

      - name: Sync
        run: |
          sync
          sudo umount mnt

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: alpine-root
          path: alpine-root.img
