name: Build VXLinux ARMHF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y \
            debootstrap \
            qemu-user-static \
            binfmt-support \
            e2fsprogs \
            xz-utils

      - name: Enable ARM emulation
        run: |
          sudo update-binfmts --enable qemu-arm || true

      - name: Create ARMHF rootfs
        run: |
          mkdir rootfs

          sudo debootstrap \
            --arch=armhf \
            --foreign \
            bookworm \
            rootfs \
            http://deb.debian.org/debian

          sudo cp /usr/bin/qemu-arm-static rootfs/usr/bin/

          sudo chroot rootfs /debootstrap/debootstrap --second-stage

      - name: Install basic packages
        run: |
          sudo chroot rootfs apt update

          sudo chroot rootfs apt install -y \
            bash \
            coreutils \
            apt \
            iproute2 \
            net-tools \
            iputils-ping \
            curl \
            wget \
            ca-certificates \
            nano \
            vim \
            python3

      - name: Create VXInit
        run: |
          sudo rm -rf rootfs/sbin/init

          sudo mkdir -p rootfs/sbin

          sudo tee rootfs/sbin/init > /dev/null <<'EOF'
#!/bin/sh

echo "======== VXInit v0.1 ========"

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true

echo "[VXINIT] Boot finished."

exec /bin/bash
EOF

          sudo chmod +x rootfs/sbin/init

      - name: Prepare rootfs directories
        run: |
          sudo mkdir -p rootfs/dev
          sudo mkdir -p rootfs/proc
          sudo mkdir -p rootfs/sys
          sudo mkdir -p rootfs/tmp
          sudo mkdir -p rootfs/run

      - name: Create ext4 disk image
        run: |
          dd if=/dev/zero \
            of=vxlinux-armhf.img \
            bs=1M \
            count=512

          mkfs.ext4 vxlinux-armhf.img

          mkdir mount

          sudo mount -o loop vxlinux-armhf.img mount

          sudo cp -a rootfs/. mount/

          sudo umount mount

      - name: Compress image
        run: |
          xz -9 vxlinux-armhf.img

      - name: Upload VXLinux image
        uses: actions/upload-artifact@v4
        with:
          name: VXLinux-armhf-rootfs
          path: vxlinux-armhf.img.xz
